const ActionTypes={
    PLUS_COUNTER:"PLUS_COUNTER",
    MINUS_COUNTER:"MINUS_COUNTER",
        // Products Section
    GET_PRODUCT_DATA:"GET_PRODUCT_DATA",
    GET_DATA_LOADING:"GET_DATA_LOADING",
    GET_DATA_SUCCESS:"GET_DATA_SUCCESS",
    GET_DATA_FAIL:"GET_DATA_FAIL",
        // Add to cart
    ADD_TO_CART:"ADD_TO_CART"
};
export {ActionTypes};